export const strings = {
  brand: "suiss",
  developer: "Developer",
  search: "Search",
  searchPlaceholder: "Search documentation",
  searchEmpty: "No results found.",
  searching: "Searching…",
  onThisPage: "On this page",
  previous: "Previous",
  next: "Next",
  documentation: "Documentation",
  getStarted: "Get started",
  explore: "Explore",
  resources: "Resources",
  learnMore: "Learn more",
  github: "GitHub",
  interfaceFamily: "Interface",
  platformFamily: "Platform",
  preAlpha: "Pre-alpha",
  copyright: "Copyright © 2026 suiss. All rights reserved.",
  license: "Released under open-source licenses.",
  heroEyebrow: "suiss Developer",
  heroTitle: "Build with suiss.",
  heroSubtitle:
    "Components for every screen and open services for identity, messaging and work — documented in one place.",
  heroPrimary: "Get started",
  heroSecondary: "Browse components",
  interfaceTitle: "Interface",
  interfaceSubtitle: "One design language for the web and for native apps.",
  platformTitle: "Platform",
  platformSubtitle:
    "Open-source services that run on infrastructure you already know.",
  docsIndexTitle: "Documentation",
  docsIndexSubtitle: "Choose a product to start.",
  menu: "Menu",
  close: "Close",
  copy: "Copy",
  copied: "Copied",
  note: "Note",
  tip: "Tip",
  important: "Important",
  warning: "Warning",
  deprecated: "Deprecated",
};
