export const strings = {
  brand: "suiss/ui",
  search: "Search",
  searchPlaceholder: "Search documentation",
  searchEmpty: "No results found.",
  searching: "Searching…",
  onThisPage: "On this page",
  previous: "Previous",
  next: "Next",
  documentation: "Documentation",
  getStarted: "Get started",
  github: "GitHub",
  copyright: "Copyright © 2026 suiss. All rights reserved.",
  license: "Released under open-source licenses.",
  heroSubtitle:
    "Copy-paste React components, patterns, interactions, charts and blocks built on Base UI and Tailwind CSS.",
  menu: "Menu",
  close: "Close",
  copy: "Copy",
  copied: "Copied",
  note: "Note",
  tip: "Tip",
  important: "Important",
  warning: "Warning",
  deprecated: "Deprecated",
};
